version: '3'

services:
  squid:
    image: docker.io/babim/squid
    depends_on:
    - nginx-proxy
  nginx:
    image: docker.io/nginx:${MATRIX_VERSION}
    volumes:
    - ../../../tests/data/nginx/:/etc/nginx:ro
  nginx-proxy:
    image: docker.io/nginx:${MATRIX_VERSION}
    volumes:
    - ../../../tests/data/nginx/:/etc/nginx:ro

networks:
  default:
    name: ${VECTOR_NETWORK}
    external: true
